mysite/bday_reminder/urls.py
from django.conf.urls import url
from . import views

app_name = 'bday_reminder'
urlpatterns = [
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^send/$', views.send, name='send'),
]

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.views.generic import RedirectView
from django.contrib import admin
import mysite.views

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='/login/')),
    url(r'^admin/', admin.site.urls),
    url(r'^bday_reminder/', include('bday_reminder.urls')),
    url(r'^login/', mysite.views.login),
    url(r'^authenticate/$', mysite.views.auth),
]

mysite/bday_reminder/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Patient(models.Model):
	first_name = models.TextField()
	last_name = models.TextField()
	email = models.TextField()
	phone = models.TextField()
	birthday = models.DateField(null=True, blank=True)
	sent = models.BooleanField(default=False)

class User_Credential(models.Model):
	access_token = models.TextField()
	refresh_token = models.TextField()
	expiry_time = models.DateTimeField(null=True, blank=True)

mysite/bday_reminder/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from bday_reminder.models import Patient
from django.core.mail import send_mail
from django.conf import settings
from datetime import date

# Create your views here.

def profile(request):
	if request.POST:
		first_name = request.POST['first_name']
		last_name = request.POST['last_name']
		email = request.POST['email']
		phone = request.POST['phone']
		birthday = request.POST['birthday']
		p = Patient(first_name=first_name, last_name=last_name, email=email, phone=phone, birthday=birthday)
		p.save()
		return HttpResponseRedirect('/bday_reminder/profile')
	else:
		args = {}
		args['patients'] = Patient.objects.all()
		return render(request, 'bday_reminder/profile.html', args)

def send(request):

	bdays = Patient.objects.all().filter(birthday__month=date.today().month,birthday__day=date.today().day)
	patients = Patient.objects.all().filter(birthday__month=date.today().month,birthday__day=date.today().day,sent=False)
	subject = 'Happy Birthday'
	message = 'Wishing you a Happy Birthday from DrChrono!'
	sender = settings.EMAIL_HOST_USER

	for patient in patients:
		p = Patient.objects.get(first_name=patient.first_name, last_name=patient.last_name, birthday__month=date.today().month, birthday__day=date.today().day, sent=False)
		p.sent = True
		p.save()
		send_mail(subject, message, sender, [patient.email], fail_silently=False)

	args = {}
	if patients:
		args['message'] = 'Birthday Reminder Sent!'
	elif not bdays:
		args['message'] = 'No birthdays today!'
	else:
		args['message'] = 'You have already sent the birthday reminders today!'

	return render(request, 'bday_reminder/send.html', args)

mysite/mysite/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
import datetime, requests, pytz
from bday_reminder.models import Patient, User_Credential
# from django.contrib.auth.models import User

def login(request):
	return render(request, 'login.html', {})

def auth(request):

	code = request.GET.get('code')

	# getting access and refresh token
	response = requests.post('https://drchrono.com/o/token/', data={
	    'code': code,
	    'grant_type': 'authorization_code',
	    'redirect_uri': 'http://127.0.0.1:8000/authenticate/',
	    'client_id': 'Ur5LSA3czS3sXFuiUH22vNTeIP7LCIa7llFxuAYr',
	    'client_secret': 'BKXg7hp2NGZgjNbqKrzGogZKViFCBKmvhOa2XLKo9fsglMQ3HwnOO2HANyimWgbntRKRhYFq6iUGjpMbmHUqLWEUK1Sm6ofKdTpWEmYVH7wIquzGLZB4g9renDMBfF3Q',
	})
	response.raise_for_status()
	data = response.json()

	# Save these in your database associated with the user
	access_token = data['access_token']
	refresh_token = data['refresh_token']
	expires_timestamp = datetime.datetime.now(pytz.utc) + datetime.timedelta(seconds=data['expires_in'])
	User_Credential.objects.all().delete()
	uc = User_Credential(access_token=access_token, refresh_token=refresh_token, expiry_time=expires_timestamp)
	uc.save()
	# response = requests.get('https://drchrono.com/api/users/current', headers={
	# 	'Authorization': 'Bearer %s' % access_token,
	# })
	# response.raise_for_status()
	# data = response.json()
	headers = {
	    'Authorization': 'Bearer %s' % access_token,
	}

	patients = []
	patients_url = 'https://drchrono.com/api/patients'
	while patients_url:
	    data = requests.get(patients_url, headers=headers).json()
	    patients.extend(data['results'])
	    patients_url = data['next'] # A JSON null on the last page

	#clear patient info in database
	Patient.objects.all().delete()

	#store patient info in database
	for patient in patients:
		first_name = patient['first_name']
		last_name = patient['last_name']
		email = patient['email']
		phone = patient['cell_phone']
		birthday = patient['date_of_birth']
		sent = False
		p = Patient(first_name=first_name, last_name=last_name, email=email, phone=phone, birthday=birthday, sent=sent)
		p.save()

	return HttpResponseRedirect('/bday_reminder/profile')

mysite/bday_reminder/templates/bday_reminder/profile.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

	<head>

		<title>Doctor Profile</title>
		<meta charset="utf-8">
	  	<meta name="viewport" content="width=device-width, initial-scale=1">
	  	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
	  	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
	  	<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
	  	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
		<link rel="stylesheet" type="text/css" href="{% static 'bday_reminder/style.css' %}" />
		<script>
			function send_emails() {
				document.getElementById("doc_profile").style.opacity="0.5";
				document.getElementById("loading_msg").style.visibility="visible";
				document.getElementById("spinner").style.visibility="visible";
				location.href='/bday_reminder/send';
			}
		</script>

	</head>

	<body>

		<div class="text-center carousel-caption" id="spinner_container">
			<h1 id="loading_msg">Sending...</h1>
			<i class="fa fa-spinner fa-spin" id="spinner"></i>
		</div>

		  <!-- Modal -->
		<div class="modal fade" id="myModal" role="dialog">
		    <div class="modal-dialog">
		    
		      <!-- Modal content-->
		      	<div class="modal-content">
		        	<div class="modal-header">
		          		<button type="button" class="close" data-dismiss="modal">&times;</button>
		          		<h4 class="modal-title">Enter Patient Information:</h4>
		        	</div>
		        	<form role="form" action="{% url 'bday_reminder:profile' %}" method="post">{% csrf_token %}
			        	<div class="modal-body">
							<div class="form-group">
								<label for="first_name">First Name:</label>
								<input class="form-control" name="first_name">
							</div>
							<div class="form-group">
								<label for="last_name">Last Name:</label>
								<input class="form-control" name="last_name">
							</div>
							<div class="form-group">
								<label for="email">Email:</label>
								<input class="form-control" name="email">
							</div>
							<div class="form-group">
								<label for="phone">Phone Number:</label>
								<input class="form-control" name="phone">
							</div>
							<div class="form-group">
								<label for="birthday">Birthday (YYYY-MM-DD):</label>
								<input class="form-control" name="birthday">
							</div>
			        	</div>
			        	<div class="modal-footer">
			          		<button type="submit" class="btn btn-default">Submit</button>
			        	</div>
		        	</form>
		      	</div>
		      
		    </div>
		</div>

		<div class="container" id="doc_profile">
            <div class="panel">
                <img class="pic img-circle" src="{% static "bday_reminder/images/doctor.jpg" %}">
                <div class="name">
                	<small>Dr. Chrono</small>
          		</div>
        	</div>
            <br><br><br>
			<div>
			  	<span class="patient_info">Patient Information</span>
			  	<button id= "bday_button" type="button" class="btn btn-success btn-md" onclick="send_emails()">Send Birthday Greeting</button>
			  	<button id= "add_button" type="button" class="btn btn-primary btn-md" data-toggle="modal" data-target="#myModal">Add User</button>
		  	</div>
           	<div class="table-responsive"> 
			  	<table class="table">
				    <thead>
				    	<tr>
				        	<th>Firstname</th>
				        	<th>Lastname</th>
				        	<th>Email</th>
				        	<th>Phone</th>
				        	<th>Birthday</th>
				      	</tr>
				    </thead>
				    <tbody>
				      	{% for patient in patients %}
						    <tr class="info">
						    	<td>{{ patient.first_name }}</td>
						        <td>{{ patient.last_name }}</td>
						        <td>{{ patient.email }}</td>
						        <td>{{ patient.phone }}</td>
						        <td>{{ patient.birthday }}</td>
						    </tr>
				      	{% endfor %}
			    	</tbody>
			  	</table>
		  	</div>
		</div>

	</body>

</html>

mysite/bday_reminder/templates/bday_reminder/send.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

	<head>

		<title>Birthday Reminder Sent</title>
		<meta charset="utf-8">
	  	<meta name="viewport" content="width=device-width, initial-scale=1">
	  	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
	  	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
		<link rel="stylesheet" type="text/css" href="{% static 'bday_reminder/style.css' %}" />

	</head>

	<body id="sent_reminders">

		<div class="birthday_reminder_msg">
			<h1 class="birthday_reminder">{{ message }}</h1>
			<button class="btn btn-default" id="back_button" onclick="location.href='/bday_reminder/profile'">Click here to go back</button>
		</div>
	</body>

</html>

mysite/templates/login.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

	<head>
		<title>Logging In</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
		<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
		<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
		<style>
			html, body{
				background-color: red;
			}
			.auth_form{
				text-align: center;
				color: black;
				width: 38%;
				border: 5px solid;
				margin: auto;
				margin-top: 8%;
			}	
			#submit_login{
				margin-bottom: 20px;
			}
			#client_id{
				width: 80%;
				margin: auto;
			}
			#url{
				width: 80%;
				margin: auto;
			}
		</style>
		<script>
			function login(){
				document.getElementById("spinner").style.visibility="visible";
				var client_id = document.getElementById("client_id").value;
				var url = document.getElementById("url").value;
				window.location.href="https://drchrono.com/o/authorize/?redirect_uri=" + url + "&response_type=code&client_id=" + client_id;
			}
		</script>
	</head>

	<body>
		<form role="form" class="auth_form">
			<h1>Enter DrChrono login credentials:</h1>
			<h6>Please enter the fields that you created in the DrChrono API web application. You will then be redirected to DrChrono's authorize URL</h6>
			<div class="form-group">
				<label for="client_id">Client ID:</label>
				<input class="form-control" id="client_id">
			</div>
			<div class="form-group">
				<label for="url">Redirect URI:</label>
				<input class="form-control" id="url">
			</div>
			<div class="btn btn-default" id="submit_login" onclick="login()">Submit</div>
		</form>
		<div class="text-center">
			<i class="fa fa-spinner fa-spin" id="spinner" style="font-size: 120px; margin-top: 10px; color: black; visibility: hidden;"></i>
		</div>
	</body>

</html>